AY2324S2-CS2113-F14-2/tp

- docs/AboutUs.md
Update about me with Zheng Wentao's information
> Update about me (Zheng Wentao)

- src/main/java/CommandType.java
- src/main/java/Parser.java
* Add CommandType and Parser classes
* Add pseudo unit test in Parser.java
> Implement parsing function

- docs/AboutUs.md
- src/main/java/model/SetMenu.java
Added categories of "breakfast", "lunch" and "dinner" for different types of set menus.
> Add enum class for set menu categories and update profile picture

- src/main/java/model/Menu.java
Implemented an initial version of the Menu class. Would use OOP to further break down the Menu into subclasses depending on the type of Menu.
> Add Menu class

- src/main/java/model/Menu.java
- src/test/java/model/MenuTest.java
Add basic unit test for addition and removal of items from a menu
> Add menu item addition/removal unit test

- MenuLogger.log
- src/main/java/model/Menu.java
Added logger for Menu class. 
Modified Menu class by removing numOfItems field because the necessary information regarding the number of items in the Menu could be retrieved from ArrayList method. 
Renamed menuItemID to menuId, because we should be working with menus as a whole and not the individual items.
> Add and integrate logger for Menu class

- src/main/java/logic/MainLogic.java
Added a default menu for v1. The menu includes 10 items.
> Add initial hardcoded menu for v1

- src/main/java/command/ViewMenuCommand.java
- src/main/java/logic/MainLogic.java
- src/main/java/model/Menu.java
- src/main/java/model/MenuItem.java
- src/main/java/ui/CommandType.java
Reverts AY2324S2-CS2113-F14-2/tp#39
> Correct version with View Menu command

- src/main/java/command/MainViewOrderCommand.java
Fix return statement to return the order searched for
> MainViewOrderCommand.java: Change return statement

- src/main/java/command/MainCreateOrderCommand.java
- src/main/java/command/MainExitCommand.java
- src/main/java/command/MainHelpCommand.java
- src/main/java/command/MainViewOrderCommand.java
- src/main/java/command/MainViewOrdersSummaryCommand.java
- src/main/java/command/OrderAddCommand.java
- src/main/java/command/OrderCompleteCommand.java
- src/main/java/command/OrderDeleteCommand.java
- src/main/java/command/OrderExitCommand.java
- src/main/java/command/OrderViewItemsCommand.java
- src/main/java/logic/MainLogic.java
* SLAP more in the MainLogic
* Modified MainCreateOrderCommand
* Modified MainViewOrderCommand
> Refactor createOrder command in MainLogic

- src/main/java/command/MenuAddCommand.java
- src/main/java/command/MenuCommand.java
- src/main/java/command/MenuHelpCommand.java
- src/main/java/logic/MenuLogic.java
- src/main/java/model/Menu.java
- src/main/java/ui/CommandType.java
Reverts AY2324S2-CS2113-F14-2/tp#73
> Correct version, Modify Menu class, add MenuLogic

- MenuLogger.log
- src/main/java/command/OrderAddCommand.java
- src/main/java/command/menu/MenuAddCommand.java
- src/main/java/command/menu/MenuDeleteCommand.java
- src/main/java/command/menu/MenuHelpCommand.java
- src/main/java/command/menu/MenuViewMenuListCommand.java
- src/main/java/command/order/OrderDeleteCommand.java
- src/main/java/logic/MenuLogic.java
- src/main/java/logic/OrderLogic.java
- src/main/java/model/Menu.java
- src/main/java/ui/CommandType.java
- src/test/java/model/MenuTest.java
Implement Menu commands including MenuAdd, MenuDelete as well as help and exit. Complete in the menu subsystem does not quite work yet. Open to suggestions!
> Implement Menu commands

- src/main/java/command/OrderAddCommand.java
- src/main/java/command/main/MainEditMenuCommand.java
- src/main/java/command/main/MainViewOrderCommand.java
- src/main/java/command/menu/MenuAddCommand.java
- src/main/java/command/menu/MenuCompleteCommand.java
- src/main/java/command/menu/MenuDeleteCommand.java
- src/main/java/command/menu/MenuExitCommand.java
- src/main/java/command/order/OrderCompleteCommand.java
- src/main/java/command/order/OrderDeleteCommand.java
- src/main/java/command/order/OrderExitCommand.java
- src/main/java/logic/MainLogic.java
- src/main/java/logic/MenuLogic.java
- src/main/java/logic/OrderLogic.java
- src/main/java/model/ItemManager.java
- src/main/java/model/Menu.java
- src/main/java/model/Order.java
- src/test/java/model/OrderTest.java
Fix syntax issues. Renamed to CamelCase for "Id" instead of "ID". Abstract out some code for the MenuLogic class.
> Refactor code and abstract out classes, format in CamelCase

- docs/UserGuide.md
Added more potential queries a user could have and the corresponding answers to those queries.
> Add FAQ in the user guide

- src/main/java/logic/MainLogic.java
- src/main/java/logic/MenuLogic.java
- src/main/java/logic/OrderLogic.java
> Add indication of which interface user is currently in

- docs/UserGuide.md
Fixed the presentation of the command summary page in the user guide.
> Fix documentation in User Guide to clarify organization structure

- src/main/java/command/main/MainEditMenuCommand.java
- src/main/java/logic/MainLogic.java
- src/main/java/model/Menu.java
- src/test/java/command/MainCommandTest.java
> Add feature to revert changes to menu after using "cancel" command

- src/main/java/command/order/OrderAddCommand.java
> Fix bug when quantity of item added to order is too large

- .gitignore
- MenuLogger.log
- OrderAddCommandLogger.log
- src/main/java/model/Order.java
The receipt is formatted as such. What do you think of it?
> Change receipt format

- src/main/java/logic/MainLogic.java
- src/main/java/logic/OrderLogic.java
User will be prompted for an input again if it is invalid as shown below. Does it look ok?
> Handle invalid inputs for restaurant details and order type

- src/main/java/command/main/MainEditMenuCommand.java
- src/main/java/logic/MainLogic.java
- src/main/java/model/Order.java
- src/main/java/model/Restaurant.java
- src/main/java/storage/Storage.java
> Add storage feature for restaurant details, menus, and orders

- src/main/java/storage/Storage.java
Bug fix for program crashing when attempting to read empty save file of restaurant details.
> Storage.java: Handle NoSuchElement exception when reading save file

- src/main/java/logic/MainLogic.java
- src/main/java/model/Restaurant.java
Remove unused variables and logic for initializeSystem() method.
> MainLogic.java: Refactor code

- docs/team/zhengwinter.md
- src/main/java/command/menu/MenuHelpCommand.java
- src/test/java/command/MenuCommandTest.java
- src/test/java/model/MenuTest.java
Added test cases for all the menu commands. Found 2 issues which has been published under "Issues".
Updated contributions on PPP.
> Add test case for menu commands and updated Zhengwinter's PPP

- src/main/java/Pair.java
- src/main/java/logic/MainLogic.java
- src/main/java/model/Item.java
- src/main/java/model/Menu.java
- src/test/java/command/MenuCommandTest.java
- src/test/java/model/MenuTest.java
* Item IDs are sorted in ascending order after each deletion
* Add a space before the price numbers
> Improve menu display

- docs/UserGuide.md
- src/main/java/command/main/MainHelpCommand.java
- src/main/java/command/stats/StatsBestSellingItemCommand.java
- src/main/java/command/stats/StatsCommand.java
- src/main/java/command/stats/StatsGrossRevenueCommand.java
- src/main/java/command/stats/StatsHelpCommand.java
- src/main/java/command/stats/StatsNetRevenueCommand.java
- src/main/java/command/stats/StatsProfitCommand.java
- src/main/java/command/stats/StatsTotalOrdersCommand.java
- src/main/java/logic/MainLogic.java
- src/main/java/logic/StatsLogic.java
- src/main/java/model/Menu.java
- src/main/java/model/MenuItem.java
- src/main/java/stats/OrderStatistics.java
- src/main/java/stats/Pair.java
- src/main/java/ui/CommandType.java
- src/test/java/command/MainCommandTest.java
* StatsLogic: separate interface from main to handle restaurant performance related commands
* StatsCommand: implementations of view all kinds of performance data
* Add new CommandTypes to facilitate StatsLogic
* Refactor stats-related classes into packages
> Add OrderStatistics related classes and variables

- OrderAddCommandLogger.log
- data/orders.txt
- src/main/java/command/menu/MenuAddCommand.java
- src/main/java/command/order/OrderAddCommand.java
- src/main/java/logic/OrderLogic.java
- src/main/java/model/Menu.java
- src/main/java/model/Order.java
* In menu interface: item price must be a number in (0, 10000); item name cannot be empty string
* Make it case-insensitive in checking items with the same name (e.g. ChIcKeN == cHICken )
* In each order, quantity for an added item must be an integer in (0, 10000) and total count capped at 9999
> Add constraints and error messages to user input values

- src/main/java/storage/Storage.java
Fix issue where users are able to enter negative values for price and item ID in `orders.txt` and `menus.txt`
> Storage.java: Fix bug relating to save file

- OrderAddCommandLogger.log
- data/orders.txt
- docs/UserGuide.md
- src/main/java/command/stats/StatsBestSellingItemCommand.java
- src/main/java/logic/MainLogic.java
- src/main/java/model/Order.java
- src/main/java/ui/CommandErrorMessage.java
- src/test/java/stats/OrderStatisticsTest.java
Fixed Bugs:
1. long userName/restaurantName/restaurantAddress issue
3. bestSelling command when no orders in the orderList
4. Discount total price not correctly shown in Main interface
> Branch fix receipt bugs

- docs/UserGuide.md
- src/main/java/logic/MainLogic.java
- src/main/java/model/Menu.java
- src/main/java/ui/CommandType.java
It is not changed to this format:   "Menu ID: %s, Number of items: %d"
> Fix bug: View menu command should show "menu <menu_id> with XX items"

- MenuLogger.log.1
- OrderAddCommandLogger.log
- data/menus.txt
- src/main/java/command/order/OrderDeleteCommand.java
- src/main/java/command/order/OrderViewItemsCommand.java
- src/test/java/command/MenuCommandTest.java
- src/test/java/command/OrderCommandTest.java
Test for various situations for all order commands.
> Add test cases for all order commands
